# Aula 4: Manipulando arquivos HTML e XML

Chegou a hora de testar os conhecimentos desenvolvidos durante a aula.

Vanessa é uma cientista de dados que está realizando algumas análises com dados ambientais. Ela está desenvolvendo um projeto para avaliar o impacto ambiental das atividades humanas em diferentes países do mundo, mas para isso precisa das estimativas populacionais desses países. Ao pesquisar na internet, encontrou uma tabela de estimativas populacionais em um artigo da página Wikipédia.

Assim como Vanessa, seu desafio é obter um DataFrame da tabela que contém as informações do número de habitantes de cada país.

In [ ]:
import pandas as pd

In [ ]:
url = 'https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o'

In [ ]:
df = pd.read_html(url)[0]
df

,Unnamed: 0,Posição,País (ou território dependente),Estimativa da ONU,Data,Estimativa Oficial
0,NaN,1,Índia,1 429 921 746,2023,Estimativa oficial
1,NaN,2,China,1 426 391 281,2023,Censo oficial
2,NaN,3,Estados Unidos,339 987 103,2023,Censo oficial
3,NaN,4,Indonésia,277 184 719,2023,Estimativa oficial
4,NaN,5,Paquistão,240 215 932,2023,Estimativa oficial
...,...,...,...,...,...,...
245,NaN,–,Ilha de Ascensão (Reino Unido),806,2021,Estimativa oficial[10]
246,NaN,195,Vaticano,801,2020,Estimativa oficial
247,NaN,–,Ilhas Cocos (Keeling) (Austrália),573,2020,Estimativa oficial
248,NaN,–,Tristão da Cunha (Reino Unido),241,2022,Estimativa oficial[11]
249,NaN,–,Ilhas Pitcairn (Reino Unido),40,2021,Estimativa oficial

In [ ]:
df.to_html('demografia_paises.html')